version: '3'
services:
  fund:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    networks:
      - net
    ports:
      - 7003:7003
      - 9889:9889
    environment:
      - JAVA_OPTS=-Xmx500M -Duser.timezone=GMT+08
      - NACOS_PUBLIC_IP=${NACOS_PUBLIC_IP}

networks:
  net:
    driver: bridge