version: '3'
services:
  fund:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fund
    networks:
      - net
    ports:
      - 7003:7003
      - 9889:9889
    environment:
      - JAVA_OPTS=-Xmx500M -Duser.timezone=GMT+08
      - SERVICE_IP=localhost
      - NACOS_PUBLIC_IP=localhost
      - XXL_PUBLIC_IP=localhost
      - TX_PUBLIC_IP=localhost
      - spring.profiles.active=prod,prod-redis,swagger

networks:
  net:
    driver: bridge