version: '3'
services:
  fund:
    image: dataanalysis-docker.pkg.coding.net/spring-cloud-haozai/image/spring-cloud-fund:latest
    container_name: fund
    networks:
      - net
    ports:
      - 7003:7003
      - 9889:9889
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08
      - NACOS_PUBLIC_IP=${NACOS_PUBLIC_IP}

networks:
  net:
    driver: bridge