version: '3'
services:
  xxl-job:
    image: dataanalysis-docker.pkg.coding.net/spring-cloud-haozai/image/xxl-job-skywalking:2.3.0
    container_name: xxl-job
    networks:
      - net
    ports:
      - 8989:8080
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://1gfco70pqu10zt81o.mysql.rds.aliyuncs.com:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=xxl_job  --spring.datasource.password=xxl_job666!
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=${SKYWALKING_IP_PORT}
      - SW_AGENT_NAME=xxl-job
      - JAVA_OPTS=-javaagent:/agent/skywalking-agent.jar
    volumes:
      - /data:/data/applogs
networks:
  net:
    driver: bridge