version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: /data/spring-cloud-haozai/gatewayDockerfile
    container_name: gateway
    networks:
      - net
    ports:
      - 7000:7000
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08
  auth:
    build:
      context: .
      dockerfile: /data/spring-cloud-haozai/authDockerfile
    container_name: gateway
    networks:
      - net
    ports:
      - 7000:7001
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08
  fund:
    build:
      context: .
      dockerfile: /data/spring-cloud-haozai/fundDockerfile
    container_name: gateway
    networks:
      - net
    ports:
      - 7000:7003
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08

networks:
  net:
    driver: bridge