version: '1'
services:
  gateway:
    build:
      context: ..
      dockerfile: /spring-cloud-gateway/docker/Dockerfile
    container_name: gateway
    networks:
      - net
    ports:
      - 7000:7000
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08
  auth:
    build:
      context: ..
      dockerfile: /spring-cloud-auth/docker/Dockerfile
    container_name: auth
    networks:
      - net
    ports:
      - 7001:7001
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08
  fund:
    build:
      context: ..
      dockerfile: /spring-cloud-fund/docker/Dockerfile
    container_name: fund
    networks:
      - net
    ports:
      - 7003:7003
      - 9889:9889
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08

networks:
  net:
    driver: bridge