version: '3'
services:
  fund:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    networks:
      - net
    ports:
      - 7000:7000
    environment:
      - JAVA_OPTS=-Xmx150M -Duser.timezone=GMT+08
      - NACOS_PUBLIC_IP=${NACOS_PUBLIC_IP}
      - XXL_PUBLIC_IP=${XXL_PUBLIC_IP}
      - TX_PUBLIC_IP=${TX_PUBLIC_IP}
      - spring.profiles.active=prod,prod-redis

networks:
  net:
    driver: bridge