version: '3'
services:
  gateway:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    networks:
      - net
    ports:
      - 7000:7000
    environment:
      - JAVA_OPTS=-Xmx150M -Duser.timezone=GMT+08
      - SERVICE_IP=${SERVICE_IP}
      - NACOS_PUBLIC_IP=${NACOS_PUBLIC_IP}
      - XXL_PUBLIC_IP=${XXL_PUBLIC_IP}
      - TX_PUBLIC_IP=${TX_PUBLIC_IP}
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=${SKYWALKING_IP_PORT}
      - spring.profiles.active=prod,prod-redis
    volumes:
      - /data/agent.config:/skywalking/agent/config
networks:
  net:
    driver: bridge