version: '3'
services:
  rabbitmq:
    image: dataanalysis-docker.pkg.coding.net/spring-cloud-haozai/image/rabbitmq-skywalking:management
    container_name: rabbitmq
    networks:
      - net
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SW_AGENT_NAME=rabbitmq
      - JAVA_OPTS=-javaagent:/agent/skywalking-agent.jar
networks:
  net:
    driver: bridge