version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - net
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
networks:
  net:
    driver: bridge