version: '3'
services:
  tx-manage:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    networks:
      - net
    ports:
      - 7005:7005
      - 8070:8070
    environment:
      - JAVA_OPTS=-Xmx100M -Duser.timezone=GMT+08

networks:
  net:
    driver: bridge